import type { MetadataRoute } from "next";

const tools = [
  "https://www.inteliglo.com/tools/air-travel-tools/baggage-fee-calculator",
  "https://www.inteliglo.com/tools/air-travel-tools/currency-converter",
  "https://www.inteliglo.com/tools/air-travel-tools/layover-time-calculator",
  "https://www.inteliglo.com/tools/air-travel-tools/visa-fee-calculator",
  "https://www.inteliglo.com/tools/developer-tools/base64",
  "https://www.inteliglo.com/tools/developer-tools/csv-to-json",
  "https://www.inteliglo.com/tools/developer-tools/html-css-js-minify",
  "https://www.inteliglo.com/tools/developer-tools/html-css-js-unminify",
  "https://www.inteliglo.com/tools/developer-tools/html-encoder-decoder",
  "https://www.inteliglo.com/tools/developer-tools/json-formatter",
  "https://www.inteliglo.com/tools/developer-tools/json-to-csv",
  "https://www.inteliglo.com/tools/developer-tools/json-validator",
  "https://www.inteliglo.com/tools/developer-tools/lorem-ipsum-generator",
  "https://www.inteliglo.com/tools/developer-tools/password-generator",
  "https://www.inteliglo.com/tools/developer-tools/regex-tester",
  "https://www.inteliglo.com/tools/developer-tools/slugify-tool",
  "https://www.inteliglo.com/tools/developer-tools/sql-formatter",
  "https://www.inteliglo.com/tools/developer-tools/timestamp-converter",
  "https://www.inteliglo.com/tools/developer-tools/url-encoder-decoder",
  "https://www.inteliglo.com/tools/developer-tools/uuid-generator",
  "https://www.inteliglo.com/tools/developer-tools/word-counter",
  "https://www.inteliglo.com/tools/developer-tools/xml-formatter",
  "https://www.inteliglo.com/tools/developer-tools/yaml-formatter",
  "https://www.inteliglo.com/tools/education-tools/cgpa-percentage-calculator",
  "https://www.inteliglo.com/tools/education-tools/education-loan-vs-scholarship-calculator",
  "https://www.inteliglo.com/tools/education-tools/study-abroad-cost-calculator",
  "https://www.inteliglo.com/tools/finance-tools/54ec-calculator",
  "https://www.inteliglo.com/tools/finance-tools/TDS Calculator",
  "https://www.inteliglo.com/tools/finance-tools/advance-tax-calculator",
  "https://www.inteliglo.com/tools/finance-tools/atal-pension-yojana",
  "https://www.inteliglo.com/tools/finance-tools/business-loan-calculator",
  "https://www.inteliglo.com/tools/finance-tools/car-loan-emi-calculator",
  "https://www.inteliglo.com/tools/finance-tools/cgt-calculator",
  "https://www.inteliglo.com/tools/finance-tools/compound-interest-calculator",
  "https://www.inteliglo.com/tools/finance-tools/credit-card-emi-interest-calculator",
  "https://www.inteliglo.com/tools/finance-tools/debt-to-income-ratio-calculator",
  "https://www.inteliglo.com/tools/finance-tools/education-loan-calculator",
  "https://www.inteliglo.com/tools/finance-tools/elss-calculator",
  "https://www.inteliglo.com/tools/finance-tools/emi-calculator",
  "https://www.inteliglo.com/tools/finance-tools/emi-vs-prepayment-calculator",
  "https://www.inteliglo.com/tools/finance-tools/epf-calculator",
  "https://www.inteliglo.com/tools/finance-tools/fd-calculator",
  "https://www.inteliglo.com/tools/finance-tools/frsb-calculator",
  "https://www.inteliglo.com/tools/finance-tools/gold-loan-calculator",
  "https://www.inteliglo.com/tools/finance-tools/gold-silver-calculator",
  "https://www.inteliglo.com/tools/finance-tools/gst-calculator",
  "https://www.inteliglo.com/tools/finance-tools/hli-calculator",
  "https://www.inteliglo.com/tools/finance-tools/home-loan-emi-calculator",
  "https://www.inteliglo.com/tools/finance-tools/hra-calculator",
  "https://www.inteliglo.com/tools/finance-tools/income-tax-calculator",
  "https://www.inteliglo.com/tools/finance-tools/inflation-calculator",
  "https://www.inteliglo.com/tools/finance-tools/kvp-calculator",
  "https://www.inteliglo.com/tools/finance-tools/loan-calculator",
  "https://www.inteliglo.com/tools/finance-tools/loan-eligibility-calculator",
  "https://www.inteliglo.com/tools/finance-tools/loan-interest-calculator",
  "https://www.inteliglo.com/tools/finance-tools/loan-tenure-calculator",
  "https://www.inteliglo.com/tools/finance-tools/lumpsum-investment-calculator",
  "https://www.inteliglo.com/tools/finance-tools/net-worth-calculator",
  "https://www.inteliglo.com/tools/finance-tools/nps-calculator",
  "https://www.inteliglo.com/tools/finance-tools/nps-tier-2-calculator",
  "https://www.inteliglo.com/tools/finance-tools/nsc-calculator",
  "https://www.inteliglo.com/tools/finance-tools/outstanding-loan-calculator",
  "https://www.inteliglo.com/tools/finance-tools/percentage-calculator",
  "https://www.inteliglo.com/tools/finance-tools/personal-loan-emi-calculator",
  "https://www.inteliglo.com/tools/finance-tools/ppf-calculator",
  "https://www.inteliglo.com/tools/finance-tools/rd-calculator",
  "https://www.inteliglo.com/tools/finance-tools/reducing-balance-loan-calculator",
  "https://www.inteliglo.com/tools/finance-tools/retirement-corpus-calculator",
  "https://www.inteliglo.com/tools/finance-tools/rule-of-72-calculator",
  "https://www.inteliglo.com/tools/finance-tools/salary-ctc-calculator",
  "https://www.inteliglo.com/tools/finance-tools/scss-calculator",
  "https://www.inteliglo.com/tools/finance-tools/sgb-calculator",
  "https://www.inteliglo.com/tools/finance-tools/simple-interest-calculator",
  "https://www.inteliglo.com/tools/finance-tools/sip-calculator",
  "https://www.inteliglo.com/tools/finance-tools/step-up-sip-calculator",
  "https://www.inteliglo.com/tools/finance-tools/sukanya-samriddhi-yojana",
  "https://www.inteliglo.com/tools/finance-tools/swp-calculator",
  "https://www.inteliglo.com/tools/finance-tools/td-calculator",
  "https://www.inteliglo.com/tools/finance-tools/ulip-calculator",
  "https://www.inteliglo.com/tools/health-tools/bmr-calorie-calculator",
  "https://www.inteliglo.com/tools/health-tools/body-fat-calculator",
  "https://www.inteliglo.com/tools/health-tools/heart-rate-zone-calculator",
  "https://www.inteliglo.com/tools/health-tools/ideal-weight-calculator",
  "https://www.inteliglo.com/tools/health-tools/macro-calculator",
  "https://www.inteliglo.com/tools/health-tools/ovulation-calculator",
  "https://www.inteliglo.com/tools/health-tools/pregnancy-due-date-calculator",
  "https://www.inteliglo.com/tools/health-tools/waist-hip-ratio-calculator",
  "https://www.inteliglo.com/tools/health-tools/water-intake-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/carpet-area-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/home-loan-affordability-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/property-appreciation-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/property-tax-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/rent-vs-buy-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/rental-yield-calculator",
  "https://www.inteliglo.com/tools/realestate-tools/stamp-duty-calculator",
  "https://www.inteliglo.com/tools/transport-tools/fuel-cost-calculator",
  "https://www.inteliglo.com/tools/transport-tools/irctc-refund-calculator",
  "https://www.inteliglo.com/tools/transport-tools/toll-cost-calculator",
  "https://www.inteliglo.com/tools/transport-tools/train-fare-calculator",
  "https://www.inteliglo.com/tools/transport-tools/waitlist-confirmation-calculator",
  "https://www.inteliglo.com/tools/utility-tools/age-calculator",
  "https://www.inteliglo.com/tools/utility-tools/bmi-calculator",
  "https://www.inteliglo.com/tools/utility-tools/date-difference-calculator",
  "https://www.inteliglo.com/tools/utility-tools/electricity-bill-calculator",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return [
    { url: "https://www.inteliglo.com", lastModified: now, changeFrequency: "weekly", priority: 1 },
    { url: "https://www.inteliglo.com/tools", lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    ...tools.map((url) => ({ url, lastModified: now, changeFrequency: "monthly" as const, priority: 0.8 })),
  ];
}
