export const toolSEO = {
  "baggage-fee-calculator": {
    name: "Flight Baggage Fee Calculator",
    title: "Flight Baggage Fee Calculator – Free Online Tool",
    description: "Use Inteliglo's free flight baggage fee calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["flight baggage fee calculator", "baggage fee calculator", "online baggage fee calculator", "free baggage fee calculator", "baggage fee calculator calculator"],
    category: "Air Travel Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/air-travel-tools/baggage-fee-calculator",
  },
  "currency-converter": {
    name: "Currency Converter",
    title: "Currency Converter – Free Online Tool",
    description: "Use Inteliglo's free currency converter online to get quick results from your inputs. Simple, fast, and easy to use from any device.",
    keywords: ["currency converter", "online currency converter", "free currency converter"],
    category: "Air Travel Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/air-travel-tools/currency-converter",
  },
  "layover-time-calculator": {
    name: "Layover Time Calculator",
    title: "Layover Time Calculator – Free Online Tool",
    description: "Use Inteliglo's free layover time calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["layover time calculator", "online layover time calculator", "free layover time calculator", "layover time calculator calculator"],
    category: "Air Travel Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/air-travel-tools/layover-time-calculator",
  },
  "visa-fee-calculator": {
    name: "Visa Fee Calculator (for Indian Passport Holders)",
    title: "Visa Fee Calculator (for Indian Passport Holders)",
    description: "Use Inteliglo's free visa fee calculator (for indian passport holders) to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["visa fee calculator (for indian passport holders)", "visa fee calculator", "online visa fee calculator", "free visa fee calculator", "visa fee calculator calculator"],
    category: "Air Travel Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/air-travel-tools/visa-fee-calculator",
  },
  "base64": {
    name: "Base64 Encoder / Decoder",
    title: "Base64 Encoder / Decoder – Free Online Tool",
    description: "Use Inteliglo's free base64 encoder / decoder online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["base64 encoder / decoder", "base64", "online base64", "free base64"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/base64",
  },
  "csv-to-json": {
    name: "CSV to JSON",
    title: "CSV to JSON – Free Online Tool",
    description: "Use Inteliglo's free csv to json online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["csv to json", "online csv to json", "free csv to json"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/csv-to-json",
  },
  "html-css-js-minify": {
    name: "Html Css Js Minify",
    title: "Html Css Js Minify – Free Online Tool",
    description: "Use Inteliglo's free html css js minify online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["html css js minify", "online html css js minify", "free html css js minify"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/html-css-js-minify",
  },
  "html-css-js-unminify": {
    name: "Html Css Js Unminify",
    title: "Html Css Js Unminify – Free Online Tool",
    description: "Use Inteliglo's free html css js unminify online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["html css js unminify", "online html css js unminify", "free html css js unminify"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/html-css-js-unminify",
  },
  "html-encoder-decoder": {
    name: "HTML Encoder / Decoder",
    title: "HTML Encoder / Decoder – Free Online Tool",
    description: "Use Inteliglo's free html encoder / decoder online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["html encoder / decoder", "html encoder decoder", "online html encoder decoder", "free html encoder decoder"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/html-encoder-decoder",
  },
  "json-formatter": {
    name: "JSON Formatter",
    title: "JSON Formatter – Free Online Tool",
    description: "Use Inteliglo's free json formatter online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["json formatter", "online json formatter", "free json formatter"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/json-formatter",
  },
  "json-to-csv": {
    name: "JSON to CSV",
    title: "JSON to CSV – Free Online Tool",
    description: "Use Inteliglo's free json to csv online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["json to csv", "online json to csv", "free json to csv"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/json-to-csv",
  },
  "json-validator": {
    name: "JSON Validator",
    title: "JSON Validator – Free Online Tool",
    description: "Use Inteliglo's free json validator online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["json validator", "online json validator", "free json validator"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/json-validator",
  },
  "lorem-ipsum-generator": {
    name: "Lorem Ipsum Generator",
    title: "Lorem Ipsum Generator – Free Online Tool",
    description: "Use Inteliglo's free lorem ipsum generator online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["lorem ipsum generator", "online lorem ipsum generator", "free lorem ipsum generator"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/lorem-ipsum-generator",
  },
  "password-generator": {
    name: "Free Random Password Generator",
    title: "Free Random Password Generator – Free Online Tool",
    description: "Use Inteliglo's free free random password generator online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["free random password generator", "password generator", "online password generator", "free password generator"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/password-generator",
  },
  "regex-tester": {
    name: "Regex Tester",
    title: "Regex Tester – Free Online Tool",
    description: "Use Inteliglo's free regex tester online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["regex tester", "online regex tester", "free regex tester"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/regex-tester",
  },
  "slugify-tool": {
    name: "Slugify — URL Slug Generator",
    title: "Slugify — URL Slug Generator – Free Online Tool",
    description: "Use Inteliglo's free slugify — url slug generator online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["slugify — url slug generator", "slugify tool", "online slugify tool", "free slugify tool"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/slugify-tool",
  },
  "sql-formatter": {
    name: "SQL Formatter",
    title: "SQL Formatter – Free Online Tool",
    description: "Use Inteliglo's free sql formatter online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["sql formatter", "online sql formatter", "free sql formatter"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/sql-formatter",
  },
  "timestamp-converter": {
    name: "Timestamp Converter",
    title: "Timestamp Converter – Free Online Tool",
    description: "Use Inteliglo's free timestamp converter online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["timestamp converter", "online timestamp converter", "free timestamp converter"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/timestamp-converter",
  },
  "url-encoder-decoder": {
    name: "URL Encoder / Decoder",
    title: "URL Encoder / Decoder – Free Online Tool",
    description: "Use Inteliglo's free url encoder / decoder online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["url encoder / decoder", "url encoder decoder", "online url encoder decoder", "free url encoder decoder"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/url-encoder-decoder",
  },
  "uuid-generator": {
    name: "UUID Generator",
    title: "UUID Generator – Free Online Tool",
    description: "Use Inteliglo's free uuid generator online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["uuid generator", "online uuid generator", "free uuid generator"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/uuid-generator",
  },
  "word-counter": {
    name: "Word Counter & Text Analyzer",
    title: "Word Counter & Text Analyzer – Free Online Tool",
    description: "Use Inteliglo's free word counter & text analyzer online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["word counter & text analyzer", "word counter", "online word counter", "free word counter"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/word-counter",
  },
  "xml-formatter": {
    name: "XML Formatter",
    title: "XML Formatter – Free Online Tool",
    description: "Use Inteliglo's free xml formatter online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["xml formatter", "online xml formatter", "free xml formatter"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/xml-formatter",
  },
  "yaml-formatter": {
    name: "YAML Formatter",
    title: "YAML Formatter – Free Online Tool",
    description: "Use Inteliglo's free yaml formatter online to work with your data or code quickly. No installation required—enter your input and get results instantly.",
    keywords: ["yaml formatter", "online yaml formatter", "free yaml formatter"],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/yaml-formatter",
  },
  "cgpa-percentage-calculator": {
    name: "CGPA to Percentage Converter",
    title: "CGPA to Percentage Converter – Free Online Tool",
    description: "Use Inteliglo's free cgpa to percentage converter to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["cgpa to percentage converter", "cgpa percentage calculator", "online cgpa percentage calculator", "free cgpa percentage calculator"],
    category: "Education Tools",
    applicationCategory: "EducationalApplication",
    path: "/tools/education-tools/cgpa-percentage-calculator",
  },
  "education-loan-vs-scholarship-calculator": {
    name: "Education Loan vs Scholarship Calculator",
    title: "Education Loan vs Scholarship Calculator – Free Online Tool",
    description: "Use Inteliglo's free education loan vs scholarship calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["education loan vs scholarship calculator", "online education loan vs scholarship calculator", "free education loan vs scholarship calculator", "education loan vs scholarship calculator calculator"],
    category: "Education Tools",
    applicationCategory: "EducationalApplication",
    path: "/tools/education-tools/education-loan-vs-scholarship-calculator",
  },
  "study-abroad-cost-calculator": {
    name: "Study Abroad Cost Calculator",
    title: "Study Abroad Cost Calculator – Free Online Tool",
    description: "Use Inteliglo's free study abroad cost calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["study abroad cost calculator", "online study abroad cost calculator", "free study abroad cost calculator", "study abroad cost calculator calculator"],
    category: "Education Tools",
    applicationCategory: "EducationalApplication",
    path: "/tools/education-tools/study-abroad-cost-calculator",
  },
  "54ec-calculator": {
    name: "54EC Bonds (Capital Gains Tax Exemption) Calculator",
    title: "54EC Bonds (Capital Gains Tax Exemption) Calculator",
    description: "Use Inteliglo's free 54ec bonds (capital gains tax exemption) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["54ec bonds (capital gains tax exemption) calculator", "54ec calculator", "online 54ec calculator", "free 54ec calculator", "54ec calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/54ec-calculator",
  },
  "TDS Calculator": {
    name: "TDS Calculator",
    title: "TDS Calculator – Free Online Tool",
    description: "Use Inteliglo's free tds calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["tds calculator", "online tds calculator", "free tds calculator", "tds calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/TDS Calculator",
  },
  "advance-tax-calculator": {
    name: "Advance Tax Calculator",
    title: "Advance Tax Calculator – Free Online Tool",
    description: "Use Inteliglo's free advance tax calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["advance tax calculator", "online advance tax calculator", "free advance tax calculator", "advance tax calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/advance-tax-calculator",
  },
  "atal-pension-yojana": {
    name: "APY (Atal Pension Yojana) Calculator",
    title: "APY (Atal Pension Yojana) Calculator – Free Online Tool",
    description: "Use Inteliglo's free apy (atal pension yojana) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["apy (atal pension yojana) calculator", "atal pension yojana", "online atal pension yojana", "free atal pension yojana", "atal pension yojana calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/atal-pension-yojana",
  },
  "business-loan-calculator": {
    name: "Business Loan Calculator",
    title: "Business Loan Calculator – Free Online Tool",
    description: "Use Inteliglo's free business loan calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["business loan calculator", "online business loan calculator", "free business loan calculator", "business loan calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/business-loan-calculator",
  },
  "car-loan-emi-calculator": {
    name: "Car Loan EMI Calculator",
    title: "Car Loan EMI Calculator – Free Online Tool",
    description: "Use Inteliglo's free car loan emi calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["car loan emi calculator", "online car loan emi calculator", "free car loan emi calculator", "car loan emi calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/car-loan-emi-calculator",
  },
  "cgt-calculator": {
    name: "Capital Gains Tax (CGT) Calculator",
    title: "Capital Gains Tax (CGT) Calculator – Free Online Tool",
    description: "Use Inteliglo's free capital gains tax (cgt) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["capital gains tax (cgt) calculator", "cgt calculator", "online cgt calculator", "free cgt calculator", "cgt calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/cgt-calculator",
  },
  "compound-interest-calculator": {
    name: "Compound Interest Calculator",
    title: "Compound Interest Calculator – Free Online Tool",
    description: "Use Inteliglo's free compound interest calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["compound interest calculator", "online compound interest calculator", "free compound interest calculator", "compound interest calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/compound-interest-calculator",
  },
  "credit-card-emi-interest-calculator": {
    name: "Credit Card EMI / Interest Calculator",
    title: "Credit Card EMI / Interest Calculator – Free Online Tool",
    description: "Use Inteliglo's free credit card emi / interest calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["credit card emi / interest calculator", "credit card emi interest calculator", "online credit card emi interest calculator", "free credit card emi interest calculator", "credit card emi interest calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/credit-card-emi-interest-calculator",
  },
  "debt-to-income-ratio-calculator": {
    name: "Debt-to-Income Ratio Calculator",
    title: "Debt-to-Income Ratio Calculator – Free Online Tool",
    description: "Use Inteliglo's free debt-to-income ratio calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["debt-to-income ratio calculator", "debt to income ratio calculator", "online debt to income ratio calculator", "free debt to income ratio calculator", "debt to income ratio calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/debt-to-income-ratio-calculator",
  },
  "education-loan-calculator": {
    name: "Education Loan Calculator",
    title: "Education Loan Calculator – Free Online Tool",
    description: "Use Inteliglo's free education loan calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["education loan calculator", "online education loan calculator", "free education loan calculator", "education loan calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/education-loan-calculator",
  },
  "elss-calculator": {
    name: "ELSS (Tax-Saving Mutual Fund) Calculator",
    title: "ELSS (Tax-Saving Mutual Fund) Calculator – Free Online Tool",
    description: "Use Inteliglo's free elss (tax-saving mutual fund) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["elss (tax-saving mutual fund) calculator", "elss calculator", "online elss calculator", "free elss calculator", "elss calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/elss-calculator",
  },
  "emi-calculator": {
    name: "EMI Calculator",
    title: "EMI Calculator – Free Online Tool",
    description: "Use Inteliglo's free emi calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["emi calculator", "online emi calculator", "free emi calculator", "emi calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/emi-calculator",
  },
  "emi-vs-prepayment-calculator": {
    name: "EMI vs Prepayment Calculator",
    title: "EMI vs Prepayment Calculator – Free Online Tool",
    description: "Use Inteliglo's free emi vs prepayment calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["emi vs prepayment calculator", "online emi vs prepayment calculator", "free emi vs prepayment calculator", "emi vs prepayment calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/emi-vs-prepayment-calculator",
  },
  "epf-calculator": {
    name: "EPF (Employees' Provident Fund) Calculator",
    title: "EPF (Employees' Provident Fund) Calculator – Free Online Tool",
    description: "Use Inteliglo's free epf (employees' provident fund) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["epf (employees' provident fund) calculator", "epf calculator", "online epf calculator", "free epf calculator", "epf calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/epf-calculator",
  },
  "fd-calculator": {
    name: "FD Calculator",
    title: "FD Calculator – Free Online Tool",
    description: "Use Inteliglo's free fd calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["fd calculator", "online fd calculator", "free fd calculator", "fd calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/fd-calculator",
  },
  "frsb-calculator": {
    name: "FRSB (Floating Rate Savings Bonds) Calculator",
    title: "FRSB (Floating Rate Savings Bonds) Calculator",
    description: "Use Inteliglo's free frsb (floating rate savings bonds) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["frsb (floating rate savings bonds) calculator", "frsb calculator", "online frsb calculator", "free frsb calculator", "frsb calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/frsb-calculator",
  },
  "gold-loan-calculator": {
    name: "Gold Loan Calculator",
    title: "Gold Loan Calculator – Free Online Tool",
    description: "Use Inteliglo's free gold loan calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["gold loan calculator", "online gold loan calculator", "free gold loan calculator", "gold loan calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/gold-loan-calculator",
  },
  "gold-silver-calculator": {
    name: "Gold / Silver Price Calculator",
    title: "Gold / Silver Price Calculator – Free Online Tool",
    description: "Use Inteliglo's free gold / silver price calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["gold / silver price calculator", "gold silver calculator", "online gold silver calculator", "free gold silver calculator", "gold silver calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/gold-silver-calculator",
  },
  "gst-calculator": {
    name: "GST Calculator",
    title: "GST Calculator – Free Online Tool",
    description: "Use Inteliglo's free gst calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["gst calculator", "online gst calculator", "free gst calculator", "gst calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/gst-calculator",
  },
  "hli-calculator": {
    name: "Life Insurance Cover Calculator",
    title: "Life Insurance Cover Calculator – Free Online Tool",
    description: "Use Inteliglo's free life insurance cover calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["life insurance cover calculator", "hli calculator", "online hli calculator", "free hli calculator", "hli calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/hli-calculator",
  },
  "home-loan-emi-calculator": {
    name: "Home Loan EMI Calculator",
    title: "Home Loan EMI Calculator – Free Online Tool",
    description: "Use Inteliglo's free home loan emi calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["home loan emi calculator", "online home loan emi calculator", "free home loan emi calculator", "home loan emi calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/home-loan-emi-calculator",
  },
  "hra-calculator": {
    name: "HRA (House Rent Allowance) Calculator",
    title: "HRA (House Rent Allowance) Calculator – Free Online Tool",
    description: "Use Inteliglo's free hra (house rent allowance) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["hra (house rent allowance) calculator", "hra calculator", "online hra calculator", "free hra calculator", "hra calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/hra-calculator",
  },
  "income-tax-calculator": {
    name: "Income Tax Calculator",
    title: "Income Tax Calculator – Free Online Tool",
    description: "Use Inteliglo's free income tax calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["income tax calculator", "online income tax calculator", "free income tax calculator", "income tax calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/income-tax-calculator",
  },
  "inflation-calculator": {
    name: "Inflation Calculator",
    title: "Inflation Calculator – Free Online Tool",
    description: "Use Inteliglo's free inflation calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["inflation calculator", "online inflation calculator", "free inflation calculator", "inflation calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/inflation-calculator",
  },
  "kvp-calculator": {
    name: "KVP (Kisan Vikas Patra) Calculator",
    title: "KVP (Kisan Vikas Patra) Calculator – Free Online Tool",
    description: "Use Inteliglo's free kvp (kisan vikas patra) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["kvp (kisan vikas patra) calculator", "kvp calculator", "online kvp calculator", "free kvp calculator", "kvp calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/kvp-calculator",
  },
  "loan-calculator": {
    name: "Loan Calculator",
    title: "Loan Calculator – Free Online Tool",
    description: "Use Inteliglo's free loan calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["loan calculator", "online loan calculator", "free loan calculator", "loan calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/loan-calculator",
  },
  "loan-eligibility-calculator": {
    name: "Loan Eligibility Calculator",
    title: "Loan Eligibility Calculator – Free Online Tool",
    description: "Use Inteliglo's free loan eligibility calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["loan eligibility calculator", "online loan eligibility calculator", "free loan eligibility calculator", "loan eligibility calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/loan-eligibility-calculator",
  },
  "loan-interest-calculator": {
    name: "Loan Interest Calculator",
    title: "Loan Interest Calculator – Free Online Tool",
    description: "Use Inteliglo's free loan interest calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["loan interest calculator", "online loan interest calculator", "free loan interest calculator", "loan interest calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/loan-interest-calculator",
  },
  "loan-tenure-calculator": {
    name: "Loan Tenure Calculator",
    title: "Loan Tenure Calculator – Free Online Tool",
    description: "Use Inteliglo's free loan tenure calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["loan tenure calculator", "online loan tenure calculator", "free loan tenure calculator", "loan tenure calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/loan-tenure-calculator",
  },
  "lumpsum-investment-calculator": {
    name: "Lumpsum Investment Calculator",
    title: "Lumpsum Investment Calculator – Free Online Tool",
    description: "Use Inteliglo's free lumpsum investment calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["lumpsum investment calculator", "online lumpsum investment calculator", "free lumpsum investment calculator", "lumpsum investment calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/lumpsum-investment-calculator",
  },
  "net-worth-calculator": {
    name: "Net Worth Calculator",
    title: "Net Worth Calculator – Free Online Tool",
    description: "Use Inteliglo's free net worth calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["net worth calculator", "online net worth calculator", "free net worth calculator", "net worth calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/net-worth-calculator",
  },
  "nps-calculator": {
    name: "NPS (National Pension System) Calculator",
    title: "NPS (National Pension System) Calculator – Free Online Tool",
    description: "Use Inteliglo's free nps (national pension system) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["nps (national pension system) calculator", "nps calculator", "online nps calculator", "free nps calculator", "nps calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/nps-calculator",
  },
  "nps-tier-2-calculator": {
    name: "NPS Tier 2 Calculator",
    title: "NPS Tier 2 Calculator – Free Online Tool",
    description: "Use Inteliglo's free nps tier 2 calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["nps tier 2 calculator", "online nps tier 2 calculator", "free nps tier 2 calculator", "nps tier 2 calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/nps-tier-2-calculator",
  },
  "nsc-calculator": {
    name: "NSC (National Savings Certificate) Calculator",
    title: "NSC (National Savings Certificate) Calculator",
    description: "Use Inteliglo's free nsc (national savings certificate) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["nsc (national savings certificate) calculator", "nsc calculator", "online nsc calculator", "free nsc calculator", "nsc calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/nsc-calculator",
  },
  "outstanding-loan-calculator": {
    name: "Outstanding Loan Calculator",
    title: "Outstanding Loan Calculator – Free Online Tool",
    description: "Use Inteliglo's free outstanding loan calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["outstanding loan calculator", "online outstanding loan calculator", "free outstanding loan calculator", "outstanding loan calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/outstanding-loan-calculator",
  },
  "percentage-calculator": {
    name: "Percentage Calculator",
    title: "Percentage Calculator – Free Online Tool",
    description: "Use Inteliglo's free percentage calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["percentage calculator", "online percentage calculator", "free percentage calculator", "percentage calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/percentage-calculator",
  },
  "personal-loan-emi-calculator": {
    name: "Personal Loan EMI Calculator",
    title: "Personal Loan EMI Calculator – Free Online Tool",
    description: "Use Inteliglo's free personal loan emi calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["personal loan emi calculator", "online personal loan emi calculator", "free personal loan emi calculator", "personal loan emi calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/personal-loan-emi-calculator",
  },
  "ppf-calculator": {
    name: "PPF Calculator",
    title: "PPF Calculator – Free Online Tool",
    description: "Use Inteliglo's free ppf calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["ppf calculator", "online ppf calculator", "free ppf calculator", "ppf calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/ppf-calculator",
  },
  "rd-calculator": {
    name: "RD (Recurring Deposit) Calculator",
    title: "RD (Recurring Deposit) Calculator – Free Online Tool",
    description: "Use Inteliglo's free rd (recurring deposit) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["rd (recurring deposit) calculator", "rd calculator", "online rd calculator", "free rd calculator", "rd calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/rd-calculator",
  },
  "reducing-balance-loan-calculator": {
    name: "Reducing Balance Loan Calculator",
    title: "Reducing Balance Loan Calculator – Free Online Tool",
    description: "Use Inteliglo's free reducing balance loan calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["reducing balance loan calculator", "online reducing balance loan calculator", "free reducing balance loan calculator", "reducing balance loan calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/reducing-balance-loan-calculator",
  },
  "retirement-corpus-calculator": {
    name: "Retirement Corpus Calculator",
    title: "Retirement Corpus Calculator – Free Online Tool",
    description: "Use Inteliglo's free retirement corpus calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["retirement corpus calculator", "online retirement corpus calculator", "free retirement corpus calculator", "retirement corpus calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/retirement-corpus-calculator",
  },
  "rule-of-72-calculator": {
    name: "Rule of 72 Calculator",
    title: "Rule of 72 Calculator – Free Online Tool",
    description: "Use Inteliglo's free rule of 72 calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["rule of 72 calculator", "online rule of 72 calculator", "free rule of 72 calculator", "rule of 72 calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/rule-of-72-calculator",
  },
  "salary-ctc-calculator": {
    name: "Salary / CTC Calculator (In-Hand Breakup)",
    title: "Salary / CTC Calculator (In-Hand Breakup) – Free Online Tool",
    description: "Use Inteliglo's free salary / ctc calculator (in-hand breakup) to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["salary / ctc calculator (in-hand breakup)", "salary ctc calculator", "online salary ctc calculator", "free salary ctc calculator", "salary ctc calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/salary-ctc-calculator",
  },
  "scss-calculator": {
    name: "SCSS (Senior Citizens Savings Scheme) Calculator",
    title: "SCSS (Senior Citizens Savings Scheme) Calculator",
    description: "Use Inteliglo's free scss (senior citizens savings scheme) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["scss (senior citizens savings scheme) calculator", "scss calculator", "online scss calculator", "free scss calculator", "scss calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/scss-calculator",
  },
  "sgb-calculator": {
    name: "SGB (Sovereign Gold Bond) Calculator",
    title: "SGB (Sovereign Gold Bond) Calculator – Free Online Tool",
    description: "Use Inteliglo's free sgb (sovereign gold bond) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["sgb (sovereign gold bond) calculator", "sgb calculator", "online sgb calculator", "free sgb calculator", "sgb calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/sgb-calculator",
  },
  "simple-interest-calculator": {
    name: "Simple Interest Calculator",
    title: "Simple Interest Calculator – Free Online Tool",
    description: "Use Inteliglo's free simple interest calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["simple interest calculator", "online simple interest calculator", "free simple interest calculator", "simple interest calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/simple-interest-calculator",
  },
  "sip-calculator": {
    name: "SIP Calculator",
    title: "SIP Calculator – Free Online Tool",
    description: "Use Inteliglo's free sip calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["sip calculator", "online sip calculator", "free sip calculator", "sip calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/sip-calculator",
  },
  "step-up-sip-calculator": {
    name: "Step-up SIP Calculator",
    title: "Step-up SIP Calculator – Free Online Tool",
    description: "Use Inteliglo's free step-up sip calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["step-up sip calculator", "step up sip calculator", "online step up sip calculator", "free step up sip calculator", "step up sip calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/step-up-sip-calculator",
  },
  "sukanya-samriddhi-yojana": {
    name: "SSY (Sukanya Samriddhi Yojana) Calculator",
    title: "SSY (Sukanya Samriddhi Yojana) Calculator – Free Online Tool",
    description: "Use Inteliglo's free ssy (sukanya samriddhi yojana) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["ssy (sukanya samriddhi yojana) calculator", "sukanya samriddhi yojana", "online sukanya samriddhi yojana", "free sukanya samriddhi yojana", "sukanya samriddhi yojana calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/sukanya-samriddhi-yojana",
  },
  "swp-calculator": {
    name: "SWP (Systematic Withdrawal Plan) Calculator",
    title: "SWP (Systematic Withdrawal Plan) Calculator – Free Online Tool",
    description: "Use Inteliglo's free swp (systematic withdrawal plan) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["swp (systematic withdrawal plan) calculator", "swp calculator", "online swp calculator", "free swp calculator", "swp calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/swp-calculator",
  },
  "td-calculator": {
    name: "TD (Post Office Time Deposit) Calculator",
    title: "TD (Post Office Time Deposit) Calculator – Free Online Tool",
    description: "Use Inteliglo's free td (post office time deposit) calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["td (post office time deposit) calculator", "td calculator", "online td calculator", "free td calculator", "td calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/td-calculator",
  },
  "ulip-calculator": {
    name: "ULIP Calculator",
    title: "ULIP Calculator – Free Online Tool",
    description: "Use Inteliglo's free ulip calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["ulip calculator", "online ulip calculator", "free ulip calculator", "ulip calculator calculator"],
    category: "Finance Tools",
    applicationCategory: "FinanceApplication",
    path: "/tools/finance-tools/ulip-calculator",
  },
  "bmr-calorie-calculator": {
    name: "BMR / Calorie Calculator",
    title: "BMR / Calorie Calculator – Free Online Tool",
    description: "Use Inteliglo's free bmr / calorie calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["bmr / calorie calculator", "bmr calorie calculator", "online bmr calorie calculator", "free bmr calorie calculator", "bmr calorie calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/bmr-calorie-calculator",
  },
  "body-fat-calculator": {
    name: "Body Fat % Calculator (US Navy Method)",
    title: "Body Fat % Calculator (US Navy Method) – Free Online Tool",
    description: "Use Inteliglo's free body fat % calculator (us navy method) to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["body fat % calculator (us navy method)", "body fat calculator", "online body fat calculator", "free body fat calculator", "body fat calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/body-fat-calculator",
  },
  "heart-rate-zone-calculator": {
    name: "Heart Rate Zone Calculator",
    title: "Heart Rate Zone Calculator – Free Online Tool",
    description: "Use Inteliglo's free heart rate zone calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["heart rate zone calculator", "online heart rate zone calculator", "free heart rate zone calculator", "heart rate zone calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/heart-rate-zone-calculator",
  },
  "ideal-weight-calculator": {
    name: "Ideal Weight Calculator",
    title: "Ideal Weight Calculator – Free Online Tool",
    description: "Use Inteliglo's free ideal weight calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["ideal weight calculator", "online ideal weight calculator", "free ideal weight calculator", "ideal weight calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/ideal-weight-calculator",
  },
  "macro-calculator": {
    name: "Macro Calculator",
    title: "Macro Calculator – Free Online Tool",
    description: "Use Inteliglo's free macro calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["macro calculator", "online macro calculator", "free macro calculator", "macro calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/macro-calculator",
  },
  "ovulation-calculator": {
    name: "Ovulation Calculator",
    title: "Ovulation Calculator – Free Online Tool",
    description: "Use Inteliglo's free ovulation calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["ovulation calculator", "online ovulation calculator", "free ovulation calculator", "ovulation calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/ovulation-calculator",
  },
  "pregnancy-due-date-calculator": {
    name: "Pregnancy Due Date Calculator",
    title: "Pregnancy Due Date Calculator – Free Online Tool",
    description: "Use Inteliglo's free pregnancy due date calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["pregnancy due date calculator", "online pregnancy due date calculator", "free pregnancy due date calculator", "pregnancy due date calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/pregnancy-due-date-calculator",
  },
  "waist-hip-ratio-calculator": {
    name: "Waist-to-Hip Ratio Calculator",
    title: "Waist-to-Hip Ratio Calculator – Free Online Tool",
    description: "Use Inteliglo's free waist-to-hip ratio calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["waist-to-hip ratio calculator", "waist hip ratio calculator", "online waist hip ratio calculator", "free waist hip ratio calculator", "waist hip ratio calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/waist-hip-ratio-calculator",
  },
  "water-intake-calculator": {
    name: "Water Intake Calculator",
    title: "Water Intake Calculator – Free Online Tool",
    description: "Use Inteliglo's free water intake calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["water intake calculator", "online water intake calculator", "free water intake calculator", "water intake calculator calculator"],
    category: "Health Tools",
    applicationCategory: "HealthApplication",
    path: "/tools/health-tools/water-intake-calculator",
  },
  "carpet-area-calculator": {
    name: "Carpet Area vs Built-up Area Converter",
    title: "Carpet Area vs Built-up Area Converter – Free Online Tool",
    description: "Use Inteliglo's free carpet area vs built-up area converter to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["carpet area vs built-up area converter", "carpet area calculator", "online carpet area calculator", "free carpet area calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/carpet-area-calculator",
  },
  "home-loan-affordability-calculator": {
    name: "Home Loan Affordability Calculator",
    title: "Home Loan Affordability Calculator – Free Online Tool",
    description: "Use Inteliglo's free home loan affordability calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["home loan affordability calculator", "online home loan affordability calculator", "free home loan affordability calculator", "home loan affordability calculator calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/home-loan-affordability-calculator",
  },
  "property-appreciation-calculator": {
    name: "Property Appreciation Calculator",
    title: "Property Appreciation Calculator – Free Online Tool",
    description: "Use Inteliglo's free property appreciation calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["property appreciation calculator", "online property appreciation calculator", "free property appreciation calculator", "property appreciation calculator calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/property-appreciation-calculator",
  },
  "property-tax-calculator": {
    name: "Property Tax Calculator",
    title: "Property Tax Calculator – Free Online Tool",
    description: "Use Inteliglo's free property tax calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["property tax calculator", "online property tax calculator", "free property tax calculator", "property tax calculator calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/property-tax-calculator",
  },
  "rent-vs-buy-calculator": {
    name: "Rent vs Buy Calculator",
    title: "Rent vs Buy Calculator – Free Online Tool",
    description: "Use Inteliglo's free rent vs buy calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["rent vs buy calculator", "online rent vs buy calculator", "free rent vs buy calculator", "rent vs buy calculator calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/rent-vs-buy-calculator",
  },
  "rental-yield-calculator": {
    name: "Rental Yield Calculator",
    title: "Rental Yield Calculator – Free Online Tool",
    description: "Use Inteliglo's free rental yield calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["rental yield calculator", "online rental yield calculator", "free rental yield calculator", "rental yield calculator calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/rental-yield-calculator",
  },
  "stamp-duty-calculator": {
    name: "Stamp Duty & Registration Charges Calculator",
    title: "Stamp Duty & Registration Charges Calculator",
    description: "Use Inteliglo's free stamp duty & registration charges calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["stamp duty & registration charges calculator", "stamp duty calculator", "online stamp duty calculator", "free stamp duty calculator", "stamp duty calculator calculator"],
    category: "Real Estate Tools",
    applicationCategory: "BusinessApplication",
    path: "/tools/realestate-tools/stamp-duty-calculator",
  },
  "fuel-cost-calculator": {
    name: "Fuel Cost Calculator",
    title: "Fuel Cost Calculator – Free Online Tool",
    description: "Use Inteliglo's free fuel cost calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["fuel cost calculator", "online fuel cost calculator", "free fuel cost calculator", "fuel cost calculator calculator"],
    category: "Transport Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/transport-tools/fuel-cost-calculator",
  },
  "irctc-refund-calculator": {
    name: "IRCTC Refund / Cancellation Calculator",
    title: "IRCTC Refund / Cancellation Calculator – Free Online Tool",
    description: "Use Inteliglo's free irctc refund / cancellation calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["irctc refund / cancellation calculator", "irctc refund calculator", "online irctc refund calculator", "free irctc refund calculator", "irctc refund calculator calculator"],
    category: "Transport Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/transport-tools/irctc-refund-calculator",
  },
  "toll-cost-calculator": {
    name: "Toll Cost Estimator",
    title: "Toll Cost Estimator – Free Online Tool",
    description: "Use Inteliglo's free toll cost estimator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["toll cost estimator", "toll cost calculator", "online toll cost calculator", "free toll cost calculator"],
    category: "Transport Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/transport-tools/toll-cost-calculator",
  },
  "train-fare-calculator": {
    name: "Train Fare Calculator",
    title: "Train Fare Calculator – Free Online Tool",
    description: "Use Inteliglo's free train fare calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["train fare calculator", "online train fare calculator", "free train fare calculator", "train fare calculator calculator"],
    category: "Transport Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/transport-tools/train-fare-calculator",
  },
  "waitlist-confirmation-calculator": {
    name: "Waiting List Confirmation Probability",
    title: "Waiting List Confirmation Probability – Free Online Tool",
    description: "Use Inteliglo's free waiting list confirmation probability to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["waiting list confirmation probability", "waitlist confirmation calculator", "online waitlist confirmation calculator", "free waitlist confirmation calculator"],
    category: "Transport Tools",
    applicationCategory: "TravelApplication",
    path: "/tools/transport-tools/waitlist-confirmation-calculator",
  },
  "age-calculator": {
    name: "Age & Date Difference Calculator",
    title: "Age & Date Difference Calculator – Free Online Tool",
    description: "Use Inteliglo's free age & date difference calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["age & date difference calculator", "age calculator", "online age calculator", "free age calculator", "age calculator calculator"],
    category: "Utility Tools",
    applicationCategory: "UtilityApplication",
    path: "/tools/utility-tools/age-calculator",
  },
  "bmi-calculator": {
    name: "BMI Calculator",
    title: "BMI Calculator – Free Online Tool",
    description: "Use Inteliglo's free bmi calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["bmi calculator", "online bmi calculator", "free bmi calculator", "bmi calculator calculator"],
    category: "Utility Tools",
    applicationCategory: "UtilityApplication",
    path: "/tools/utility-tools/bmi-calculator",
  },
  "date-difference-calculator": {
    name: "Date Difference Calculator",
    title: "Date Difference Calculator – Free Online Tool",
    description: "Use Inteliglo's free date difference calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["date difference calculator", "online date difference calculator", "free date difference calculator", "date difference calculator calculator"],
    category: "Utility Tools",
    applicationCategory: "UtilityApplication",
    path: "/tools/utility-tools/date-difference-calculator",
  },
  "electricity-bill-calculator": {
    name: "Electricity Bill Calculator",
    title: "Electricity Bill Calculator – Free Online Tool",
    description: "Use Inteliglo's free electricity bill calculator to calculate results quickly online. Enter your values to get an instant estimate and make informed decisions.",
    keywords: ["electricity bill calculator", "online electricity bill calculator", "free electricity bill calculator", "electricity bill calculator calculator"],
    category: "Utility Tools",
    applicationCategory: "UtilityApplication",
    path: "/tools/utility-tools/electricity-bill-calculator",
  },
  "whatsapp-link-generator": {
    name: "WhatsApp Number Link Generator",
    title: "WhatsApp Link Generator - Create wa.me Chat Links | Inteliglo",
    description:
      "Generate a direct WhatsApp chat link (wa.me) for any phone number with an optional prefilled message. Free, fast, and works without saving the contact.",
    keywords: [
      "whatsapp link generator",
      "wa.me link generator",
      "whatsapp click to chat",
      "create whatsapp link",
      "whatsapp chat link without saving number",
    ],
    category: "Utility Tools",
    applicationCategory: "UtilityApplication",
    path: "/tools/utility-tools/whatsapp-link-generator",
  },
  "html-css-js-formatter": {
    name: "HTML CSS JS Formatter",
    title: "HTML CSS JS Formatter - Beautify Code Online | Inteliglo",
    description:
      "Format and beautify HTML, CSS, and JavaScript code online. Free developer tool with customizable indentation and instant formatting.",
    keywords: [
      "html formatter",
      "html beautifier",
      "css formatter",
      "css beautifier",
      "javascript formatter",
      "javascript beautifier",
      "js formatter",
      "html css js formatter",
      "code formatter online",
      "online code beautifier",
    ],
    category: "Developer Tools",
    applicationCategory: "DeveloperApplication",
    path: "/tools/developer-tools/html-css-js-formatter",
  },
} as const;
